// Generates src/tables.ts from vendored libwebp sources, so the big constant
// tables (coeff probs, quant lookups) are extracted mechanically instead of
// hand-copied. Regenerate with: node harness/gen-tables.ts

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const LIBWEBP = join(ROOT, "vendor", "libwebp", "src");

/** Extract the C initializer for `name` from `source`, as a JS array literal. */
function extractArray(source: string, name: string): string {
  const start = source.indexOf(name);
  if (start < 0) throw new Error(`${name} not found`);
  const open = source.indexOf("{", start);
  let depth = 0;
  let end = open;
  for (let i = open; i < source.length; i++) {
    if (source[i] === "{") depth++;
    else if (source[i] === "}") {
      depth--;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  const body = source
    .slice(open, end)
    .replace(/\/\/[^\n]*/g, "") // line comments
    .replace(/\/\*[\s\S]*?\*\//g, "") // block comments
    .replace(/\{/g, "[")
    .replace(/\}/g, "]")
    .replace(/,\s*\]/g, "]"); // trailing commas
  // sanity: must be parseable JSON after bracket conversion
  JSON.parse(body);
  return body;
}

const treeEnc = readFileSync(join(LIBWEBP, "enc", "tree_enc.c"), "utf8");
const quantDec = readFileSync(join(LIBWEBP, "dec", "quant_dec.c"), "utf8");
const backRefs = readFileSync(join(LIBWEBP, "enc", "backward_references_enc.c"), "utf8");

const coeffsProba0 = extractArray(treeEnc, "VP8CoeffsProba0");
const coeffsUpdateProba = extractArray(treeEnc, "VP8CoeffsUpdateProba");
const dcTable = extractArray(quantDec, "kDcTable");
const acTable = extractArray(quantDec, "kAcTable");

const out = `// GENERATED by harness/gen-tables.ts from libwebp sources — do not edit.
// Source: libwebp (BSD-3-Clause, Copyright Google Inc.), src/enc/tree_enc.c
// and src/dec/quant_dec.c. Values are bitstream constants from RFC 6386.

/* eslint-disable */

/** RFC 6386 §13.5 default coefficient probabilities [type][band][ctx][proba]. */
export const COEFFS_PROBA0: number[][][][] = ${coeffsProba0};

/** RFC 6386 §13.4 coefficient probability update probabilities. */
export const COEFFS_UPDATE_PROBA: number[][][][] = ${coeffsUpdateProba};

/** RFC 6386 §14.1 DC dequantization lookup, indexed by QP 0..127. */
export const DC_TABLE: number[] = ${dcTable};

/** RFC 6386 §14.1 AC dequantization lookup, indexed by QP 0..127. */
export const AC_TABLE: number[] = ${acTable};

/** Zigzag scan order: coefficient n is stored at block position ZIGZAG[n]. */
export const ZIGZAG: number[] = [0, 1, 4, 8, 5, 2, 3, 6, 9, 12, 13, 10, 7, 11, 14, 15];

/** Coefficient position -> probability band (VP8EncBands, incl. sentinel). */
export const BANDS: number[] = [0, 1, 2, 3, 6, 4, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 0];

/** Extra-bit probabilities for large-level categories (RFC 6386 §13.2). */
export const CAT3: number[] = [173, 148, 140];
export const CAT4: number[] = [176, 155, 140, 135];
export const CAT5: number[] = [180, 157, 141, 134, 130];
export const CAT6: number[] = [254, 254, 243, 230, 196, 177, 153, 140, 133, 130, 129];

/** VP8L distance → 2D plane-code LUT (backward_references_enc.c). */
export const PLANE_TO_CODE: number[] = ${extractArray(backRefs, "plane_to_code_lut")};
`;

writeFileSync(join(ROOT, "src", "tables.ts"), out);
console.log("wrote src/tables.ts");
